twitter:
    name: 'jordanhudgens'
    consumer_key: '0m80uNoGPRC8N0cuoxzxgfAd5'
    consumer_secret: 'Is25uSmSqe3R8YBQ2BiZBJUCehxFliQFbAqQsFpMOz9FnALHIz'
    oauth_token: '18362376-eXx1QgFTCEFEhyRymNHlsdmsfv3iOfcuymQso5rfD'
    oauth_token_secret: '22SvgeFK7t1BSD46sqWGpYIC7xOwc0e1p11YhHJKBpA6v'